
modLoader="javafml"
loaderVersion="[43,)"
license="All rights reserved"

[[mods]]
modId="vmh_breeding"
version="1.1.6-1.19.3"
displayName="VMH - Breeding"

logoFile="vmh.png"
authors="Rikurob"

description='''
Adds configurable variety to mob sizes, and other attributes when breeding that comes from the parents values!
'''
[[dependencies.vmh_breeding]]
    modId="forge"
    mandatory=true
    versionRange="[44,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.vmh_breeding]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.3,1.20)"
    ordering="NONE"
    side="BOTH"

[[dependencies.vmh_breeding]]
    modId="pehkui"
    mandatory=true
    versionRange="[3.6.2,)"
    ordering="NONE"
    side="BOTH"
